"""empty message

Revision ID: 90080a1a0c36
Revises: 645ef7494de9
Create Date: 2025-01-04 19:49:53.678806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90080a1a0c36'
down_revision = '645ef7494de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('People',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('img', sa.String(length=250), nullable=True),
    sa.Column('skills', sa.String(length=100), nullable=True),
    sa.Column('color_eyes', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Fav_People',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_people', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_people'], ['People.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Fav_Planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_planet', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_planet'], ['Planet.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('img', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('climate', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('population', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Planet', schema=None) as batch_op:
        batch_op.drop_column('population')
        batch_op.drop_column('climate')
        batch_op.drop_column('img')
        batch_op.drop_column('description')

    op.drop_table('Fav_Planet')
    op.drop_table('Fav_People')
    op.drop_table('People')
    # ### end Alembic commands ###
